import { Roboto } from 'next/font/google'
import './globals.css'
import { NextAuthProvider } from "./providers";

const roboto = Roboto({ subsets: ['latin'], weight: "400"})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}
